# EC11 Rotary Encoder
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

# OLED
CONFIG_ZMK_DISPLAY=y
CONFIG_ZMK_DISPLAY_STATUS_SCREEN_BUILT_IN=y

# Bluetooth device name
CONFIG_ZMK_KEYBOARD_NAME="MACROPAD"
