name: Build ZMK Firmware

on:
  push:
    paths-subset:
      - 'config/**'
      - 'build.yaml'
  workflow_dispatch:

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
